# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e118e7ee216306ccbc93df4b4c2f2dbf"
name = "wishlist-app"
handle = "wishlist-app-189"
application_url = "https://coming-cologne-arm-issues.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "la-tienda-de-jaco.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products"

[auth]
redirect_urls = [
  "https://coming-cologne-arm-issues.trycloudflare.com/auth/callback",
  "https://coming-cologne-arm-issues.trycloudflare.com/auth/shopify/callback",
  "https://coming-cologne-arm-issues.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
